[build]
  command = "rm -rf flutter && git clone https://github.com/flutter/flutter.git -b stable && export PATH=\"$PATH:`pwd`/flutter/bin\" && flutter build web --dart-define=BACKEND_URL=$BACKEND_URL"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
